version: '3.6'
services:
  # 認可コンテナ
  keycloak:
    build:
      context: keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/export/test_service.json
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
    ports:
      - "18080:8080"
    volumes:
      - ./keycloak/export/test_service.json:/tmp/export/test_service.json
    depends_on:
      - mysql
  # keycloak外部ストレージ
  mysql:
    image: mysql:5.7
    volumes:
      - key_cloak_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  # APIゲートウェイ(nginx)
  nginx-gateway:
    build:
      context: gateway/nginx
    depends_on:
      - keycloak
      - api
    ports:
      - "8080:80"
  # APIゲートウェイ(node)
  node-gateway:
    build:
      context: gateway/node-js
    depends_on:
      - keycloak
      - api
    ports:
      - "8080:8000"
  # 保護対象API
  api:
    build:
      context: json-server
    volumes:
      - ./json-server/:/data

volumes:
  key_cloak_mysql_data:
    driver: local
