name: build
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: checkout
      - uses: actions/checkout@v2
      - name: compose up nginx
        run: docker-compose up -d nginx-gateway
      - name: compose up node
        run: docker-compose up -d node-gateway
